name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: centos:7
      env:
        GITHUB_WORKSPACE: ${{ github.workspace }}
      volumes:
        - ${{ github.workspace }}:${{ github.workspace }}

    steps:
      - uses: actions/checkout@v3

      - name: Install deps
        run: |
          yum install -y git
          
      - name: Run tests
        run: |
          cd tests
          export ec2pinit_debug=2
          bash run_tests.sh

  docs:
    runs-on: ubuntu-latest
    container:
      image: centos:7
      env:
        GITHUB_WORKSPACE: ${{ github.workspace }}
      volumes:
        - ${{ github.workspace }}:${{ github.workspace }}

    steps:
      - uses: actions/checkout@v3

      - name: Install deps
        run: |
          yum install -y git make doxygen graphviz
          
      - name: Build HTML documentation
        run: |
          cd docs
          doxygen
